plugins {
    id 'java'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = mod_version
group = 'plz.lizi.supersteve'
archivesBaseName = 'super-steve'

minecraft {
    mappings channel: 'parchment', version: '2023.09.03-1.20.1'

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    copyIdeResources = true

    runs {
        client {
        }

        server {
        }

        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                examplemod {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets {
    main {
        java {
            // 1. 将你的自定义文件夹添加为源码路径
            srcDir 'src/jd/java'
        }
    }
}

// 2. 阻止它被编译成 .class 文件
compileJava {
    // 这里的路径是相对于上面定义的各个 srcDirs 内部的相对路径
    // 如果想排除整个文件夹下的所有内容，使用 **/
    // exclude '/org/benf/**'
    // exclude '/org/benf/jetbrains/**'
}

// 3. 阻止它作为资源文件被打包进 JAR
jar {
    // 确保任何残余文件或同名资源不会被打包进去
    exclude '/org/benf/**'
    exclude '/org/jetbrains/**'
}

repositories {
    //flatDir {
   // }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

