modLoader="javafml"
loaderVersion="[47,)"
license="null"

[[mods]]
modId="supersteve"
version="${mod_version}"
displayName="SuperSteve"
displayURL=""
credits=""
authors="PLZLiZi"

[[dependencies.supersteve]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"
